# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 03:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='account_id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='summoner_id',
        ),
    ]
