# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 03:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20171203_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='account_id',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='summoner_id',
            field=models.BigIntegerField(default=0),
        ),
    ]
