# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 03:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20171203_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='in_game_id',
            field=models.CharField(max_length=30),
        ),
    ]
