# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 04:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20171203_2214'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('champion_id', models.CharField(max_length=4, unique=True)),
                ('champion_name', models.CharField(max_length=15, unique=True)),
                ('img_splash', models.CharField(max_length=100, unique=True)),
                ('img_icon', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
