# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 04:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_staticdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StaticData',
        ),
    ]
